apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"ipaas-testing","name":"ipaas-keycloak-1","uid":"f10f1b66-ff4f-11e6-8418-0e4452489d53","apiVersion":"v1","resourceVersion":"287774215"}}
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: ipaas-keycloak
    openshift.io/deployment.name: ipaas-keycloak-1
    openshift.io/scc: restricted
    pod.alpha.kubernetes.io/init-containers: '[{"name":"openshift-ca-pemtokeystore","image":"jimmidyson/pemtokeystore:v0.2.0","args":["-keystore","/tls-keystore/openshift-truststore.jks","-ca-file","/var/run/secrets/kubernetes.io/serviceaccount/ca.crt","-ca-file","/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt","-ca-dir","/usr/share/ca-certificates/mozilla"],"resources":{},"volumeMounts":[{"name":"ipaas-keycloak-tls","mountPath":"/tls-keystore"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}]'
    pod.beta.kubernetes.io/init-containers: '[{"name":"openshift-ca-pemtokeystore","image":"jimmidyson/pemtokeystore:v0.2.0","args":["-keystore","/tls-keystore/openshift-truststore.jks","-ca-file","/var/run/secrets/kubernetes.io/serviceaccount/ca.crt","-ca-file","/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt","-ca-dir","/usr/share/ca-certificates/mozilla"],"resources":{},"volumeMounts":[{"name":"ipaas-keycloak-tls","mountPath":"/tls-keystore"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}]'
  creationTimestamp: 2017-03-02T13:55:55Z
  generateName: ipaas-keycloak-1-
  labels:
    app: redhat-ipaas
    component: ipaas-keycloak
    deployment: ipaas-keycloak-1
    deploymentconfig: ipaas-keycloak
  name: ipaas-keycloak-1-9ncvh
  namespace: ipaas-testing
  resourceVersion: "287775425"
  selfLink: /api/v1/namespaces/ipaas-testing/pods/ipaas-keycloak-1-9ncvh
  uid: f47ddd56-ff4f-11e6-8418-0e4452489d53
spec:
  containers:
  - args:
    - -b
    - 0.0.0.0
    - -Dkeycloak.import=/opt/jboss/keycloak/standalone/configuration/ipaas-realm.json
    - -Dkeycloak.migration.strategy=IGNORE_EXISTING
    - -Djavax.net.ssl.trustStore=/opt/jboss/keycloak/standalone/configuration/tls/openshift-truststore.jks
    env:
    - name: KEYCLOAK_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: ipaas-keycloak-admin
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: ipaas-keycloak-admin
    image: docker.io/jimmidyson/keycloak-openshift@sha256:d6e6024148ab9dd3051ceb7fd0392eb3af6c998b3638aa401fa478db88165bee
    imagePullPolicy: IfNotPresent
    name: ipaas-keycloak
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /auth
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - NET_RAW
        - SETGID
        - SETUID
        - SYS_CHROOT
      privileged: false
      runAsUser: 1001070000
      seLinuxOptions:
        level: s0:c33,c7
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /opt/jboss/keycloak/standalone/configuration/standalone.xml
      name: ipaas-keycloak-config
      subPath: config/standalone.xml
    - mountPath: /opt/jboss/keycloak/standalone/configuration/ipaas-realm.json
      name: ipaas-keycloak-config
      subPath: config/ipaas-realm.json
    - mountPath: /opt/jboss/keycloak/standalone/configuration/tls
      name: ipaas-keycloak-tls
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-eswoh
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-340ct
  nodeName: ip-172-31-61-169.ec2.internal
  nodeSelector:
    type: compute
  restartPolicy: Always
  securityContext:
    fsGroup: 1001070000
    seLinuxOptions:
      level: s0:c33,c7
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: standalone.xml
        path: config/standalone.xml
      - key: ipaas-realm.json
        path: config/ipaas-realm.json
      name: ipaas-keycloak-config
    name: ipaas-keycloak-config
  - emptyDir: {}
    name: ipaas-keycloak-tls
  - name: default-token-eswoh
    secret:
      defaultMode: 420
      secretName: default-token-eswoh
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-03-02T13:55:55Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-03-02T13:55:55Z
    message: 'containers with unready status: [ipaas-keycloak]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-03-02T13:55:55Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://7f3614df135c8c31e539b7eb92c2b36704c4fbd3a9183030197c5a189bca5835
    image: docker.io/jimmidyson/keycloak-openshift@sha256:d6e6024148ab9dd3051ceb7fd0392eb3af6c998b3638aa401fa478db88165bee
    imageID: docker-pullable://docker.io/jimmidyson/keycloak-openshift@sha256:d6e6024148ab9dd3051ceb7fd0392eb3af6c998b3638aa401fa478db88165bee
    lastState:
      terminated:
        containerID: docker://ac94ff7b0e776373aba60a2b3a969639b08f84428b70dc1aa739bed892917111
        exitCode: 1
        finishedAt: 2017-03-02T13:56:17Z
        reason: Error
        startedAt: 2017-03-02T13:56:09Z
    name: ipaas-keycloak
    ready: false
    restartCount: 2
    state:
      terminated:
        containerID: docker://7f3614df135c8c31e539b7eb92c2b36704c4fbd3a9183030197c5a189bca5835
        exitCode: 1
        finishedAt: 2017-03-02T13:56:40Z
        reason: Error
        startedAt: 2017-03-02T13:56:32Z
  hostIP: 172.31.61.169
  phase: Running
  podIP: 10.1.0.4
  startTime: 2017-03-02T13:55:55Z
